// Tipos de erro específicos da API
export type ApiErrorCode =
  // Autenticação
  | "INVALID_TOKEN"
  | "INVALID_EMAIL_OR_PASSWORD"
  | "INVALID_REFRESH_TOKEN"
  | "TOKEN_NOT_FOUND"
  | "UNAUTHORIZED"
  | "EMAIL_NOT_VERIFIED"
  | "EXCESSIVE_LOGIN_ATTEMPTS"
  | "TOO_MANY_LOGIN_ATTEMPTS"
  | "USER_NOT_AUTHORIZED"
  | "REFRESH_TOKEN_REQUIRED"
  // Validação de dados
  | "INVALID_NAME"
  | "INVALID_EMAIL"
  | "INVALID_PASSWORD"
  | "INVALID_CONTENT"
  | "INVALID_TITLE"
  | "INVALID_DESCRIPTION"
  | "INVALID_IMAGE_FORMAT"
  | "INVALID_IMAGE_TYPE"
  | "EXCEEDED_MAX_SIZE"
  | "INVALID_PROFILE"
  | "INVALID_DATA"
  | "INVALID_TARGET"
  | "INVALID_ID"
  | "INVALID_PAGE"
  | "INVALID_QUANTITY"
  | "INVALID_SEARCH"
  | "INVALID_STATUS"
  | "INVALID_FEEDBACK"
  | "INVALID_AUTOBIOGRAPHY"
  | "INVALID_LINK"
  | "LINK_TOO_LONG"
  | "LINKS_MUST_BE_ARRAY"
  | "TAGS_MUST_BE_ARRAY"
  | "TAGS_TOO_LONG"
  | "EMAIL_REQUIRED"
  | "PASSWORD_REQUIRED"
  | "USERNAME_REQUIRED"
  // Ideias
  | "COMPLETELY_EMPTY_POST"
  | "TOO_MANY_LINKS"
  | "TOO_MANY_TAGS"
  | "TOO_MANY_IMAGES"
  | "AT_LEAST_ONE_IMAGE_IS_REQUIRED"
  | "YOU_ARE_NOT_THE_AUTHOR"
  | "THAT_IS_NOT_YOUR_IDEA"
  | "IDEA_NOT_FOUND"
  | "IDEA_ALREADY_LIKED"
  | "IDEA_NOT_LIKED"
  | "INVALID_IDEA_ID"
  | "INVALID_TARGET_IDEA_ID"
  // Comentários
  | "COMMENT_NOT_FOUND"
  | "COMMENT_ALREADY_LIKED"
  | "COMMENT_NOT_LIKED"
  | "INVALID_PARENT_COMMENT_ID"
  // Usuários
  | "USER_NOT_FOUND"
  | "USER_ALREADY_EXISTS"
  | "CANNOT_FOLLOW_SELF"
  | "YOU_CANNOT_FOLLOW_YOURSELF"
  | "ALREADY_FOLLOWING"
  | "NOT_FOLLOWING"
  | "INVALID_USER_PROFILE_ID"
  | "INVALID_TARGET_USER_ID"
  // Projetos
  | "PROJECT_NOT_FOUND"
  | "INVALID_PROJECT_ID"
  | "INVALID_TARGET_PROJECT_ID"
  | "INVALID_MEMBER_ID"
  | "YOU_ARE_NOT_THE_OWNER"
  | "YOU_CANNOT_REMOVE_THE_OWNER"
  // Colaboração
  | "COLLABORATION_REQUEST_NOT_FOUND"
  | "COLLABORATION_REQUEST_IS_NOT_PENDING"
  | "PENDING_COLLABORATION_REQUEST_ALREADY_EXISTS"
  | "PENDING_COLLABORATION_REQUEST_NOT_FOUND"
  | "YOU_CANNOT_REQUEST_COLLABORATION_FOR_YOUR_OWN_IDEA"
  | "INVALID_COLLABORATION_REQUEST_ID"
  // Chat
  | "CHAT_NOT_FOUND"
  | "INVALID_CHAT_ID"
  | "INVALID_MESSAGE"
  | "MESSAGE_TOO_LONG"
  | "YOU_CANNOT_START_CHAT_FOR_ANOTHER_USER_IDEA"
  | "INVALID_REQUESTER_ID"
  // Notificações
  | "INVALID_NOTIFICATION_ID"
  | "INVALID_NOTIFICATION_IDS"
  | "INVALID_NOTIFICATION_TYPE"
  | "INVALID_IS_READ"
  // Likes
  | "INVALID_TARGET_LIKE_ID"
  | "INVALID_LIKE_TYPE"
  // Upload de arquivos
  | "PICTURE_UPDATE_FAIL"
  // Provedores
  | "PROVIDER_NOT_FOUND"
  // Email
  | "ERROR_WHILE_CHECKING_EMAIL"
  | "ERROR_WHILE_SENDING_EMAIL"
  // Dados gerais
  | "NOT_FOUNDED_DATA"
  // Banco de dados
  | "DATABASE_ERROR"
  | "TRANSACTION_CONFLICT"
  | "QUERY_TIMEOUT"
  // Códigos de status HTTP
  | "BAD_REQUEST"
  | "FORBIDDEN"
  | "CONFLICT"
  | "UNPROCESSABLE_ENTITY"
  | "TOO_MANY_REQUESTS"
  | "INTERNAL_SERVER_ERROR"
  | "SERVICE_UNAVAILABLE";

// Interface para resposta de erro da API
export interface ApiErrorResponse {
  message: ApiErrorCode;
  statusCode: number;
  timestamp: string;
  path: string;
}

// Interface para erro customizado
export interface CustomError {
  code: ApiErrorCode;
  message: string;
  statusCode?: number;
}
