name: Build and Release Expo App

on:
  push:
    branches: [build-production]

jobs:
  build:
    name: Build Expo App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Instalar Expo CLI e EAS CLI
        run: npm install -g expo-cli eas-cli

      - name: Autenticar no Expo
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV
      
      - name: Prebuildar app
        run: expo prebuild --platform android --non-interactive

      - name: Buscar a última versão e gerar a próxima
        id: versioning
        run: |
          LAST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [[ -z "$LAST_TAG" ]]; then
            NEW_VERSION="1.0.0"
          else
            MAJOR=$(echo $LAST_TAG | cut -d. -f1)
            MINOR=$(echo $LAST_TAG | cut -d. -f2)
            PATCH=$(echo $LAST_TAG | cut -d. -f3)

            if [[ "$PATCH" -lt 9 ]]; then
              PATCH=$((PATCH + 1))
            else
              PATCH=0
              if [[ "$MINOR" -lt 9 ]]; then
                MINOR=$((MINOR + 1))
              else
                MINOR=0
                MAJOR=$((MAJOR + 1))
              fi
            fi

            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Nova versão será: $NEW_VERSION"

      - name: env config
        run: |
          echo "EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}" >> .env && \
          echo "EXPO_PUBLIC_GITHUB_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GITHUB_CLIENT_ID }}" >> .env && \
          echo "EXPO_PUBLIC_LINKEDIN_CLIENT_ID=${{ secrets.EXPO_PUBLIC_LINKEDIN_CLIENT_ID }}" >> .env && \
          echo "EXPO_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.EXPO_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env

      - name: Build app
        run: eas build --platform android --profile production --non-interactive --local --output=gamix.apk

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: "Release v${{ env.NEW_VERSION }}"
          body: "Nova versão do aplicativo Expo."
          draft: false
          prerelease: false
          files: gamix.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GHP }}
